# Generated by Django 2.2 on 2023-02-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clientemaliaddress',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='联系人邮箱'),
        ),
        migrations.AlterField(
            model_name='client',
            name='clientstate',
            field=models.CharField(max_length=10, verbose_name='客户所在省(区、市)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='clientstreet',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='客户所在街道'),
        ),
    ]
