# Generated by Django 2.2 on 2023-02-22 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20230222_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='outletno',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='app01.Outlet', verbose_name='门店编号'),
        ),
    ]
