# Generated by Django 2.2 on 2023-02-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20230222_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalagreement',
            name='insurancecovertype',
            field=models.IntegerField(blank=True, choices=[(1, '交强险'), (2, '商业险')], null=True, verbose_name='保险种类'),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='policyno',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='合同编号'),
        ),
    ]
