# Generated by Django 2.2 on 2023-02-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20230222_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='nodoors',
            field=models.CharField(max_length=17, verbose_name='车门号'),
        ),
    ]
