# Generated by Django 2.2 on 2023-02-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20230222_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='nodoors',
            field=models.CharField(max_length=10, verbose_name='车牌号'),
        ),
    ]
